version: "3.8" 

services:
  proxy:
    image: nginx:latest   
    container_name: nginx 
    ports: 
      - "80:80"          
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf 
    restart: "unless-stopped" 
  express:
    build:
      context: ./server  
    container_name: server
  
    volumes:
      - ./server:/server 
      - /server/node_modules 
    restart: "unless-stopped"