version: "3.8" 

services:
  proxy:
    image: nginx:latest   
    container_name: nginx 
    ports: 
      - "80:80"    
      - "443:443"      
    volumes:
      - ./proxy/cert.crt:/etc/nginx/cert.crt
      - ./proxy/private.key:/etc/nginx/private.key
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf 
    restart: "unless-stopped" 
  express:
    container_name: server
    build:
      context: ./  

    restart: "unless-stopped"